#配置数据源
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:image-search}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: ${DB_USER:root}
      password: ${DB_PWD:Aq1sw2de}
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 15
      # 最大连接数
      max-active: 30
      # 超时时间(以秒数为单位)
      remove-abandoned-timeout: 180
      # 获取连接超时时间
      max-wait: 3000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
      test-while-idle: true
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      # 是否在归还到池中前进行检验
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# 登录相关配置
login:
  # 登录缓存
  cache-enable: true
  #  是否限制单用户登录
  single-login: false
  #  验证码
  login-code:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    height: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体
    font-name:
    # 字体大小
    font-size: 25

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#是否开启 swagger-ui
swagger:
  enabled: true

# IP 本地解析
ip:
  local-parsing: true

# 文件存储路径
file:
  mac:
    path: ~/file/
    avatar: ~/avatar/
    imageRootPath: /Users/calvin/Documents/image_root/ # 图片文件根目录
  linux:
    path: /home/calvin/file/
    avatar: /home/calvin/avatar/
    imageRootPath: /home/aias/file/image_root/ #图片文件根目录
  windows:
    path: P:/aias/file/
    avatar: P:/aias/avatar/
    imageRootPath: P:/aias/file/image_root/ #图片文件根目录
  # 文件大小 /M
  maxSize: 1000
  avatarMaxSize: 5

image:
  # 读取图片并发数 <---------------------------------------------------1
  readerNum: 10
  # 分批次提取特征，的批次大小
  batchSize: 20480
  # 读取图片缓冲区图片数量，太大内存会溢出
  # 环形队列长度必须是2的N次方
  bufferSize: 2048
  # 图片处理并发数, 小于 cpu 核心总数 <--------------------2
  threadNum: 34
  #  path: P:/aias/file/image_root/ # 图片存放文件夹
  # 大图url <---------------------------------------------------------3
  # http://127.0.0.1:8080/aias/
  # https://www.xxxx.com/aias/
  baseUrl:  http://127.0.0.1:8080/aias/
  # 小图url <---------------------------------------------------------4
  # http://127.0.0.1:8080/thumbnail/
  # https://www.xxxx.com/thumbnail/
  thumbnailUrl: http://127.0.0.1:8080/thumbnail/

# Model URI
model:
  # P:/aias/models/CLIP-ViT-B-32-IMAGE.pt
  # /Users/calvin/products/4_apps/image_search/image-search/models/CLIP-ViT-B-32-IMAGE.pt
  imageModel: P:/aias/models/CLIP-ViT-B-32-IMAGE.pt
  poolSize: 64



##################### 向量引擎 ###############################
search:
#  host: 127.0.0.1
  host: 192.168.1.220
  port: 19530

  # https://milvus.io/cn/docs/v2.0.0/build_index.md
  # https://milvus.io/cn/docs/v2.0.0/metric.md#floating
  # For floating point vectors:
  #  IVF_FLAT
  #  IVF_SQ8
  #  IVF_PQ
  #  HNSW
  #  ANNOY
  #  RHNSW_FLAT
  #  RHNSW_PQ
  #  RHNSW_SQ
  # For binary vectors:
  #  BIN_IVF_FLAT
  indexType: IVF_FLAT
  metricType: L2

  nprobe: 256
  # https://milvus.io/docs/performance_faq.md
  nlist: 4472
  dimension: 512 #dimension of each vector
  collectionName: arts #collection name
  partitionName: p1